# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 09:54
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_auto_20180206_1054'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('team_rooster', '0009_auto_20180128_1156'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('matches', '0002_auto_20180205_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('number', models.PositiveSmallIntegerField(help_text='Add the unique number of this Match.', unique=True)),
                ('starts_at', models.DateTimeField()),
                ('team_1_color', colorfield.fields.ColorField(blank=True, default='#ff0000', max_length=18)),
                ('team_1_score', models.PositiveSmallIntegerField(blank=True)),
                ('team_2_color', colorfield.fields.ColorField(blank=True, default='#0066ff', max_length=18)),
                ('team_2_score', models.PositiveSmallIntegerField(blank=True)),
                ('team_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='team_rooster.TeamRooster')),
                ('team_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='team_rooster.TeamRooster')),
            ],
            options={
                'verbose_name_plural': 'matches',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='match',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_2',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
