# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 13:04
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team_rooster', '0014_auto_20180205_1356'),
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupstageScreencastRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupstageTournamentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(help_text='Add the unique number of this Match.')),
                ('starts_at', models.DateTimeField()),
                ('team_1_dress', colorfield.fields.ColorField(blank=True, default='#ff0000', max_length=18)),
                ('team_1_first_halftime_score', models.PositiveSmallIntegerField(blank=True, default='')),
                ('team_1_first_halftime_point', models.PositiveSmallIntegerField(blank=True, default='')),
                ('team_1_second_halftime_score', models.PositiveSmallIntegerField(blank=True, default='')),
                ('team_1_second_halftime_point', models.PositiveSmallIntegerField(blank=True, default='')),
                ('team_1_shootout_score', models.PositiveSmallIntegerField(blank=True, default='')),
                ('team_1_shootout_point', models.PositiveSmallIntegerField(blank=True, default='')),
                ('team_1_total_score', models.PositiveSmallIntegerField(blank=True, default='')),
                ('team_1_total_points', models.PositiveSmallIntegerField(blank=True, default='')),
                ('team_2_dress', colorfield.fields.ColorField(blank=True, default='#0066ff', max_length=18)),
                ('team_2_first_halftime_score', models.PositiveSmallIntegerField(blank=True, default='')),
                ('team_2_first_halftime_point', models.PositiveSmallIntegerField(blank=True, default='')),
                ('team_2_second_halftime_score', models.PositiveSmallIntegerField(blank=True, default='')),
                ('team_2_second_halftime_point', models.PositiveSmallIntegerField(blank=True, default='')),
                ('team_2_shootout_score', models.PositiveSmallIntegerField(blank=True, default='')),
                ('team_2_shootout_point', models.PositiveSmallIntegerField(blank=True, default='')),
                ('team_2_total_score', models.PositiveSmallIntegerField(blank=True, default='')),
                ('team_2_total_points', models.PositiveSmallIntegerField(blank=True, default='')),
                ('team_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='team_rooster.TeamRooster')),
                ('team_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='team_rooster.TeamRooster')),
            ],
            options={
                'verbose_name': 'Gruppenphase Spiel',
                'verbose_name_plural': 'Gruppenphase',
            },
        ),
        migrations.CreateModel(
            name='ScreencastPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='groupstagescreencastrelationship',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_screen_relationship', to='tournament.GroupstageTournamentModel'),
        ),
        migrations.AddField(
            model_name='groupstagescreencastrelationship',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupstage_screencast_relationship', to='tournament.ScreencastPage'),
        ),
    ]
