# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 10:12
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_auto_20180206_1054'),
        ('team_rooster', '0014_auto_20180205_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalphaseTournamentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(help_text='Add the unique number of this Match.')),
                ('starts_at', models.DateTimeField()),
                ('team_1_dress', colorfield.fields.ColorField(blank=True, default='#ff0000', max_length=18)),
                ('team_1_first_halftime_score', models.PositiveSmallIntegerField(blank=True)),
                ('team_1_second_halftime_score', models.PositiveSmallIntegerField(blank=True)),
                ('team_1_shootout_score', models.PositiveSmallIntegerField(blank=True)),
                ('team_2_dress', colorfield.fields.ColorField(blank=True, default='#0066ff', max_length=18)),
                ('team_2_first_halftime_score', models.PositiveSmallIntegerField(blank=True)),
                ('team_2_second_halftime_score', models.PositiveSmallIntegerField(blank=True)),
                ('team_2_shootout_score', models.PositiveSmallIntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'Finalphase Spiel',
                'verbose_name_plural': 'Finalphase',
            },
        ),
        migrations.CreateModel(
            name='GroupstageTournamentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(help_text='Add the unique number of this Match.')),
                ('starts_at', models.DateTimeField()),
                ('team_1_dress', colorfield.fields.ColorField(blank=True, default='#ff0000', max_length=18)),
                ('team_1_first_halftime_score', models.PositiveSmallIntegerField(blank=True)),
                ('team_1_second_halftime_score', models.PositiveSmallIntegerField(blank=True)),
                ('team_1_shootout_score', models.PositiveSmallIntegerField(blank=True)),
                ('team_2_dress', colorfield.fields.ColorField(blank=True, default='#0066ff', max_length=18)),
                ('team_2_first_halftime_score', models.PositiveSmallIntegerField(blank=True)),
                ('team_2_second_halftime_score', models.PositiveSmallIntegerField(blank=True)),
                ('team_2_shootout_score', models.PositiveSmallIntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'Gruppenphase Spiel',
                'verbose_name_plural': 'Gruppenphase',
            },
        ),
        migrations.CreateModel(
            name='ScreencastPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TournamentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('starts_at', models.DateTimeField(blank=True)),
                ('ends_at', models.DateTimeField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FinalphaseScreencastRelationship',
            fields=[
                ('finalphasetournamentmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tournament.FinalphaseTournamentModel')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_phase_relationship', to='tournament.ScreencastPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('tournament.finalphasetournamentmodel', models.Model),
        ),
        migrations.CreateModel(
            name='FinalphaseTournamentRelationship',
            fields=[
                ('finalphasetournamentmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tournament.FinalphaseTournamentModel')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_phase_relationship', to='tournament.TournamentPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('tournament.finalphasetournamentmodel', models.Model),
        ),
        migrations.CreateModel(
            name='GroupstageScreencastRelationship',
            fields=[
                ('groupstagetournamentmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tournament.GroupstageTournamentModel')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupstage_relationship', to='tournament.ScreencastPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('tournament.groupstagetournamentmodel', models.Model),
        ),
        migrations.CreateModel(
            name='GroupstageTournamentRelationship',
            fields=[
                ('groupstagetournamentmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tournament.GroupstageTournamentModel')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupstage_relationship', to='tournament.TournamentPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('tournament.groupstagetournamentmodel', models.Model),
        ),
        migrations.AddField(
            model_name='groupstagetournamentmodel',
            name='team_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='team_rooster.TeamRooster'),
        ),
        migrations.AddField(
            model_name='groupstagetournamentmodel',
            name='team_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='team_rooster.TeamRooster'),
        ),
        migrations.AddField(
            model_name='finalphasetournamentmodel',
            name='team_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='team_rooster.TeamRooster'),
        ),
        migrations.AddField(
            model_name='finalphasetournamentmodel',
            name='team_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='team_rooster.TeamRooster'),
        ),
    ]
