# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 13:56
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='number',
            field=models.PositiveSmallIntegerField(verbose_name='Match №:'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='starts_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='team_rooster.TeamRooster', verbose_name='Erste Team'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_1_dress',
            field=colorfield.fields.ColorField(blank=True, max_length=18, verbose_name='Dress'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_1_first_halftime_point',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Punkte 1. HZ'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_1_first_halftime_score',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Resultat 1. HZ'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_1_second_halftime_point',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Punkte 2. HZ'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_1_second_halftime_score',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Resultat 2. HZ'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_1_shootout_point',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Schootout Punkte'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_1_shootout_score',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Resultat Shootout'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_1_total_points',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Punkte Total'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_1_total_score',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Resultat Total'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='team_rooster.TeamRooster', verbose_name='Zweite Team'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_2_dress',
            field=colorfield.fields.ColorField(blank=True, default='#ff0000', max_length=18, verbose_name='Dress'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_2_first_halftime_point',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Punkte 1. HZ'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_2_first_halftime_score',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Resultat 1. HZ'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_2_second_halftime_point',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Punkte 2. HZ'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_2_second_halftime_score',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Resultat 2. HZ'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_2_shootout_point',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Schootout Punkte'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_2_shootout_score',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Resultat Shootout'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_2_total_points',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Punkte Total'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_2_total_score',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Resultat Total'),
        ),
    ]
