# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupstagetournamentrelationship',
            name='groupstagetournamentmodel_ptr',
        ),
        migrations.AddField(
            model_name='groupstagescreencastrelationship',
            name='match',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tournament.GroupstageTournamentModel'),
        ),
        migrations.AddField(
            model_name='groupstagetournamentmodel',
            name='team_1_first_halftime_point',
            field=models.PositiveSmallIntegerField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='groupstagetournamentmodel',
            name='team_1_second_halftime_point',
            field=models.PositiveSmallIntegerField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='groupstagetournamentmodel',
            name='team_1_shootout_point',
            field=models.PositiveSmallIntegerField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='groupstagetournamentmodel',
            name='team_1_total_points',
            field=models.PositiveSmallIntegerField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='groupstagetournamentmodel',
            name='team_1_total_score',
            field=models.PositiveSmallIntegerField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='groupstagetournamentmodel',
            name='team_2_first_halftime_point',
            field=models.PositiveSmallIntegerField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='groupstagetournamentmodel',
            name='team_2_second_halftime_point',
            field=models.PositiveSmallIntegerField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='groupstagetournamentmodel',
            name='team_2_shootout_point',
            field=models.PositiveSmallIntegerField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='groupstagetournamentmodel',
            name='team_2_total_points',
            field=models.PositiveSmallIntegerField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='groupstagetournamentmodel',
            name='team_2_total_score',
            field=models.PositiveSmallIntegerField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='groupstagetournamentrelationship',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupstagetournamentrelationship',
            name='match',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tournament.GroupstageTournamentModel'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_1_first_halftime_score',
            field=models.PositiveSmallIntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_1_second_halftime_score',
            field=models.PositiveSmallIntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_1_shootout_score',
            field=models.PositiveSmallIntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='team_rooster.TeamRooster'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_2_first_halftime_score',
            field=models.PositiveSmallIntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_2_second_halftime_score',
            field=models.PositiveSmallIntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_2_shootout_score',
            field=models.PositiveSmallIntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentrelationship',
            name='page',
            field=modelcluster.fields.ParentalKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupstage_relationship', to='tournament.TournamentPage'),
        ),
    ]
