# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-13 21:03
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_auto_20180212_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='number',
            field=models.PositiveSmallIntegerField(verbose_name='Match №:'),
        ),
    ]
