# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-13 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_auto_20180213_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_1_first_halftime_point',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Punkte 1. HZ'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_1_first_halftime_score',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Resultat 1. HZ'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_1_second_halftime_point',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Punkte 2. HZ'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_1_second_halftime_score',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Resultat 2. HZ'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_1_shootout_point',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Schootout Punkte'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_1_shootout_score',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Resultat Shootout'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_1_total_points',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Punkte Total'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_1_total_score',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Resultat Total'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_2_first_halftime_point',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Punkte 1. HZ'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_2_first_halftime_score',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Resultat 1. HZ'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_2_second_halftime_point',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Punkte 2. HZ'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_2_second_halftime_score',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Resultat 2. HZ'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_2_shootout_point',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Schootout Punkte'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_2_shootout_score',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Resultat Shootout'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_2_total_points',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Punkte Total'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_2_total_score',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Resultat Total'),
        ),
    ]
