# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-10 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_auto_20180214_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_1_first_halftime_score',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Resultat 1. HZ'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_1_second_halftime_score',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Resultat 2. HZ'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_1_shootout_score',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Resultat Shootout'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_2_first_halftime_score',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Resultat 1. HZ'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_2_second_halftime_score',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Resultat 2. HZ'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentmodel',
            name='team_2_shootout_score',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Resultat Shootout'),
        ),
    ]
