# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-12 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_auto_20180310_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupstagetournamentmodel',
            name='finalphase',
            field=models.BooleanField(default=False, verbose_name='Final'),
        ),
        migrations.AddField(
            model_name='groupstagetournamentmodel',
            name='is_game_finished',
            field=models.BooleanField(default=False, verbose_name='Finished'),
        ),
    ]
