# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newsindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='date_published',
            field=models.DateField(blank=True, null=True, verbose_name='Date article published'),
        ),
    ]
