# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields
import wagtailmodelchooser.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spieler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.IntegerField()),
                ('name', models.CharField(default='', max_length=100)),
                ('vorname', models.CharField(default='', max_length=100)),
                ('position', models.CharField(default='', max_length=100)),
                ('jahrgang', models.IntegerField()),
                ('photo', models.URLField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('vorname', models.CharField(default='', max_length=100)),
                ('position', models.CharField(default='', max_length=100)),
                ('photo', models.URLField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TeamRooster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(default='', max_length=100)),
                ('team_logo', models.URLField(default='', max_length=255)),
                ('staff', wagtail.wagtailcore.fields.StreamField((('staff', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='team_rooster.staff')),), blank=True, null=True, verbose_name='')),
                ('spieler', wagtail.wagtailcore.fields.StreamField((('spieler', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='team_rooster.spieler')),), blank=True, null=True, verbose_name='')),
            ],
        ),
    ]
