# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks
import wagtailblocks_cards.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRooster',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('team_name', models.CharField(default='', max_length=100)),
                ('staff', wagtail.wagtailcore.fields.StreamField((('staff', wagtailblocks_cards.blocks.CardsBlock(wagtail.wagtailcore.blocks.StructBlock((('photo', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), ('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('vorname', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('position', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('headcouch', 'Headcouch'), ('assistenz', 'Assistenz-Coach'), ('betreuer', 'Betreuer')], icon='cup')))), icon='plus')),), blank=True, default='')),
                ('spieler', wagtail.wagtailcore.fields.StreamField((('spieler', wagtailblocks_cards.blocks.CardsBlock(wagtail.wagtailcore.blocks.StructBlock((('photo', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), ('nummer', wagtail.wagtailcore.blocks.IntegerBlock(required=True)), ('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('vorname', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('position', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('th', 'TH'), ('st', 'ST'), ('vt', 'VT')], icon='cup')), ('jahrgang', wagtail.wagtailcore.blocks.IntegerBlock(required=True)))), icon='user')),), blank=True, default='')),
                ('team_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
