# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 13:28
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks
import wagtailblocks_cards.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('team_rooster', '0002_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamrooster',
            name='staff',
            field=wagtail.wagtailcore.fields.StreamField((('staff', wagtailblocks_cards.blocks.CardsBlock(wagtail.wagtailcore.blocks.StructBlock((('photo', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), ('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('vorname', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('position', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('Headcouch', 'Headcouch'), ('Assistenz-Coach', 'Assistenz-Coach'), ('Betreuer', 'Betreuer')], icon='cup')))), icon='plus')),), blank=True),
        ),
    ]
