# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_rooster', '0005_auto_20180119_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='use_other_template',
        ),
    ]
