# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_rooster', '0007_teams_teams_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='teams_page',
        ),
    ]
