# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_rooster', '0008_remove_teams_teams_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teams',
            options={},
        ),
        migrations.AddField(
            model_name='teams',
            name='introduction',
            field=models.TextField(blank=True, help_text='Text to describe the page'),
        ),
    ]
