# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 10:09
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks
import wagtailblocks_cards.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('team_rooster', '0009_auto_20180128_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamrooster',
            name='spieler',
            field=wagtail.wagtailcore.fields.StreamField((('spieler', wagtailblocks_cards.blocks.CardsBlock(wagtail.wagtailcore.blocks.StructBlock((('photo', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), ('nummer', wagtail.wagtailcore.blocks.IntegerBlock(required=True)), ('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('vorname', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('position', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('th', 'TH'), ('st', 'ST'), ('vt', 'VT')], icon='cup')))), icon='user')),), blank=True),
        ),
    ]
