# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 12:56
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks
import wagtailblocks_cards.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('team_rooster', '0013_auto_20180205_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamrooster',
            name='spieler',
            field=wagtail.wagtailcore.fields.StreamField((('spieler', wagtailblocks_cards.blocks.CardsBlock(wagtail.wagtailcore.blocks.StructBlock((('photo', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), ('nummer', wagtail.wagtailcore.blocks.IntegerBlock(required=True)), ('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('vorname', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('position', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('th', 'TH'), ('st', 'ST'), ('vt', 'VT')], icon='cup')), ('jahrgang', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[(1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], label='year', max_length=4)))), icon='user')),), blank=True),
        ),
    ]
