# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='teams_page',
            field=models.ForeignKey(blank=True, help_text='Choose a page to link to for the Team Rooster Page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Choose '),
        ),
    ]
