# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0004_auto_20180128_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='presentation_screen_section',
            field=models.ForeignKey(blank=True, help_text='Choose a page to link to for the Presentation Screen Page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Presentation Screen'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='presentation_screen_section_title',
            field=models.CharField(blank=True, help_text='Title to display above the News section on Home page', max_length=255, null=True),
        ),
    ]
