# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100)),
                ('staff_vorname', models.CharField(max_length=100)),
                ('staff_position', models.CharField(max_length=100)),
                ('foto', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TeamRooster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('vorname', models.CharField(max_length=100)),
                ('pos', models.CharField(max_length=100)),
                ('jahrgang', models.IntegerField()),
                ('foto', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('off_name', models.CharField(max_length=100)),
                ('logo_url', models.URLField(max_length=255)),
            ],
        ),
    ]
