# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamRooster', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teams',
        ),
        migrations.RenameField(
            model_name='teamrooster',
            old_name='jahrgang',
            new_name='sp_jahrgang',
        ),
        migrations.RenameField(
            model_name='teamrooster',
            old_name='nr',
            new_name='sp_nr',
        ),
        migrations.RemoveField(
            model_name='teamrooster',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='teamrooster',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teamrooster',
            name='pos',
        ),
        migrations.RemoveField(
            model_name='teamrooster',
            name='vorname',
        ),
        migrations.AddField(
            model_name='staff',
            name='team_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teamrooster',
            name='sp_foto',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='teamrooster',
            name='sp_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teamrooster',
            name='sp_pos',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teamrooster',
            name='sp_vorname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='foto',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_position',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_vorname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
